In [2]:
#Codigo para crear una lista del diccionario que nos dan
import pandas as pd
excel1='C:/BD_Diccionario.csv'
df2 = pd.read_csv(excel1,sep =";")
Lista_Nombres = df2['Nombre'].tolist()
#Lista_Nombres
#Codigo para comparar los encabezados de la tabla con la lista del diccionario
excel2='C:/BD_Limpieza_Ejercicio.csv'
df = pd.read_csv(excel2,sep =";")
importar_encabezados = df.axes[1]
#print(importar_encabezados)
for i in importar_encabezados:
    if i not in Lista_Nombres:
        df = df.drop(columns=i)
        #print(i)
#Codigo que nos indica cuanta informacion Null tiene cada columna
#df.replace(["999"],np.nan,inplace=True)
#df.replace(["."],np.nan,inplace=True)
for column in df.columns:
    #df[column]=df[column].astype(str).str.upper()
    df[column]=df[column].astype(str).str.replace("à","O")
    df[column]=df[column].astype(str).str.replace("µ","Á")
    df[column]=df[column].astype(str).str.replace("NN","N")
    df[column]=df[column].astype(str).str.replace("@","A")
    df[column]=df[column].astype(str).str.replace("Ö","Í")
    df[column]=df[column].astype(str).str.replace("CC","C")
    df[column]=df[column].astype(str).str.replace("¥","NI")
    df[column]=df[column].astype(str).str.replace("II","I")
    df[column]=df[column].astype(str).str.replace("COTA","COSTA")
    df[column]=df[column].astype(str).str.replace("TULCMN","TULCAN")
    df[column]=df[column].astype(str).str.replace("D3LEG","DÉLEG")
    df[column]=df[column].astype(str).str.replace("CONCLUIDO","TERMINADO")

#for column in df.columns:
 #   Lista = df[column].tolist()
  #  Set = set(Lista)
df.dropna()
df

,ANIO_CREACION,REG_NAT,DEMAR_HIDRO,DIR_ZON,DPA_PROVIN,DPA_DESPRO,DPA_CANTON,DPA_DESCAN,DPA_PARROQ,DPA_DESPAR,AREA,NAM,EDEL,SUP_HA
0,2021.0,REGIÓN SIERRA O INTERANDINA,DEMARCACION HIDROGRÁFICA PASTAZA,DIRECIÓN ZONAL CHIMBORAZO,5,COTOPAXI,0501,LATACUNGA,050150,LATACUNGA,URBANO,SANTA ELENA,TERMINADO,"166,498875"
1,2021.0,REGIÓN SIERRA O INTERANDINA,DEMARCACION HIDROGRÁFICA GUAYAS,DIRECIÓN ZONAL GUAYAS,2,BOLÍVAR,0201,GUARANDA,020157,SAN SIMÓN,RURAL,SAN SIMÓN DE QUINLLUNGA-GUARANDA,TERMINADO,"556,577508"
2,2021.0,REGIÓN SIERRA O INTERANDINA,DEMARCACION HIDROGRÁFICA PASTAZA,DIRECIÓN ZONAL CHIMBORAZO,nan,TUNGURAHuA,1806,QUERO,180650,QUERO,URBANO,TELIGOTE,TERMINADO,"1,825835"
3,2021.0,REGIÓN SIERRA O INTERANDINA,DEMARCACION HIDROGRÁFICA PASTAZA,DIRECIÓN ZONAL CHIMBORAZO,18,TUNGURAHUA,1807,SAN PEDRO DE PELILEO,180750,PELILEO,URBANO,TELIGOTE,TERMINADO,"193,884743"
4,2021.0,REGIÓN SIERRA O INTERANDINA,DEMARCACION HIDROGRÁFICA PASTAZA,DIRECIÓN ZONAL CHIMBORAZO,18,TUNGURAUA,1807,SAN PEDRO DE PELILEO,180752,BOLÍVAR,RURAL,TELIGOTE,TERMINADO,"2,391932"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63,2020.0,.,.,.,.,.,.,.,.,.,.,.,.,.
64,2020.0,.,.,.,.,.,.,.,.,.,.,.,.,.
65,2020.0,.,999,.,.,.,.,.,.,.,.,.,.,.
66,2020.0,.,.,.,.,.,.,.,.,.,.,.,.,.
67,2020.0,.,.,999,.,.,.,.,.,.,.,.,.,.